services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      NODE_ENV: development
      TWITTER_USERNAME: ${TWITTER_USERNAME}
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    # command: ["${TWITTER_USERNAME}"]
    # Uncomment if your app exposes a web server
    # ports:
    #   - '3000:3000'

volumes:
  pgdata:
  app_node_modules:
